@server=http://localhost:4000
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZGlkYXNtYmFsYW55YUBnbWFpbC5jb20iLCJpYXQiOjE1ODg1OTU3MjUsImV4cCI6MTU4ODU5NjYyNX0.swIj7TgD-KI_09kYr47hXCLHb-e9LG-yAoxz4lUCRxM
@refreshToken=

POST {{server}}/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  register(registerInput:{
    title:"    Software Engineer",
    description: "Mainly Backend Engineer",
    firstname: "Didas"
    lastname:"Mbalanya"
    email: "    didasmbalanya3@gmail.com    "
    gender:"MAle"
    username:"obione"
    password:"Didas12"
    github:"github.com"
    linkedin:"linkedin.com"
    phone:"+254705520482"
    phoneAlt:"+250786922399"
  })
}
###

POST {{server}}/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  login(email:"didasmbalanya@gmail.com", password: "Didas12"){
    accessToken
  }
}
###

POST  {{server}}/refresh_token
Content-Type: application/json


###
POST {{server}}/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: {{accessToken}}

query {
  me{
    id
    title
    description
    firstname
    lastname
    email
    gender
    github
    linkedin
    phone
    phoneAlt
  }
}
###
POST {{server}}/graphql
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  expireRefreshToken(userId:1)
}